-- Dining Dispatch V0 schema
-- Sized for ~700 restaurants plus related verification, menu, note, FAQ, and collection rows.

create table public.restaurants (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text,
  neighborhood text not null,
  address text,
  lat numeric(9, 6),
  lng numeric(9, 6),
  cuisine text[] not null default '{}',
  price_range text not null,
  experience_type text,
  website text,
  instagram text,
  hours jsonb not null default '{}'::jsonb,
  reservation_platform text,
  reservation_url text,
  reservation_difficulty text not null default 'moderate',
  reservation_lead_days integer,
  reservation_tips text,
  best_for text[] not null default '{}',
  avoid_for text[] not null default '{}',
  ambiance text,
  ideal_moment text,
  visitor_type text,
  tags text[] not null default '{}',
  confidence_score numeric(5, 2),
  last_verified date,
  featured boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint restaurants_price_range_check
    check (price_range in ('$', '$$', '$$$', '$$$$')),
  constraint restaurants_reservation_difficulty_check
    check (reservation_difficulty in ('walk_in', 'easy', 'moderate', 'hard', 'very_hard')),
  constraint restaurants_confidence_score_check
    check (confidence_score is null or (confidence_score >= 0 and confidence_score <= 100)),
  constraint restaurants_slug_format_check
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table public.verifications (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  source text not null,
  information_checked text not null,
  date_checked date not null,
  confidence numeric(5, 2) not null,
  notes text,
  constraint verifications_confidence_check
    check (confidence >= 0 and confidence <= 100)
);

create table public.menus (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  menu_type text not null,
  name text not null,
  currency text not null default 'MXN',
  price numeric(12, 2),
  items jsonb not null default '[]'::jsonb,
  vegetarian_options boolean not null default false,
  source text,
  last_verified date,
  notes text,
  constraint menus_menu_type_check
    check (menu_type in ('tasting', 'omakase', 'a_la_carte', 'lunch', 'dinner', 'weekend', 'other'))
);

create table public.notes (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  author text not null,
  date date not null,
  context text,
  note text not null
);

create table public.faqs (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  question text not null,
  answer text not null,
  sort_order integer not null default 0
);

create table public.collections (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  intent text,
  seo_title text,
  seo_description text,
  constraint collections_slug_format_check
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table public.collection_restaurants (
  collection_id bigint not null references public.collections (id) on delete cascade,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  sort_order integer not null default 0,
  primary key (collection_id, restaurant_id)
);

create index restaurants_neighborhood_idx on public.restaurants (neighborhood);
create index restaurants_last_verified_idx on public.restaurants (last_verified desc nulls last);
create index restaurants_price_range_idx on public.restaurants (price_range);
create index restaurants_published_idx on public.restaurants (published) where published = true;
create index restaurants_featured_idx on public.restaurants (featured) where featured = true;
create index restaurants_cuisine_gin_idx on public.restaurants using gin (cuisine);
create index restaurants_tags_gin_idx on public.restaurants using gin (tags);
create index restaurants_best_for_gin_idx on public.restaurants using gin (best_for);

create index verifications_restaurant_id_idx on public.verifications (restaurant_id);
create index verifications_date_checked_idx on public.verifications (date_checked desc);

create index menus_restaurant_id_idx on public.menus (restaurant_id);
create index menus_last_verified_idx on public.menus (last_verified desc nulls last);

create index notes_restaurant_id_idx on public.notes (restaurant_id);
create index notes_date_idx on public.notes (date desc);

create index faqs_restaurant_id_idx on public.faqs (restaurant_id);
create index faqs_sort_order_idx on public.faqs (restaurant_id, sort_order);

create index collection_restaurants_restaurant_id_idx
  on public.collection_restaurants (restaurant_id);

alter table public.restaurants enable row level security;
alter table public.verifications enable row level security;
alter table public.menus enable row level security;
alter table public.notes enable row level security;
alter table public.faqs enable row level security;
alter table public.collections enable row level security;
alter table public.collection_restaurants enable row level security;

create policy restaurants_public_read
  on public.restaurants
  for select
  to anon, authenticated
  using (published = true);

create policy verifications_public_read
  on public.verifications
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.restaurants r
      where r.id = verifications.restaurant_id
        and r.published = true
    )
  );

create policy menus_public_read
  on public.menus
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.restaurants r
      where r.id = menus.restaurant_id
        and r.published = true
    )
  );

create policy notes_public_read
  on public.notes
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.restaurants r
      where r.id = notes.restaurant_id
        and r.published = true
    )
  );

create policy faqs_public_read
  on public.faqs
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.restaurants r
      where r.id = faqs.restaurant_id
        and r.published = true
    )
  );

create policy collections_public_read
  on public.collections
  for select
  to anon, authenticated
  using (true);

create policy collection_restaurants_public_read
  on public.collection_restaurants
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.restaurants r
      where r.id = collection_restaurants.restaurant_id
        and r.published = true
    )
  );

grant usage on schema public to anon, authenticated;
grant select on table public.restaurants to anon, authenticated;
grant select on table public.verifications to anon, authenticated;
grant select on table public.menus to anon, authenticated;
grant select on table public.notes to anon, authenticated;
grant select on table public.faqs to anon, authenticated;
grant select on table public.collections to anon, authenticated;
grant select on table public.collection_restaurants to anon, authenticated;
